version: '3.9'

services:
  bind9:
    container_name: DNS-Server
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=EUROPE/AMSTERDAM
    ports:
      - 53:53/udp
      - 53:53/tcp
    volumes:
      - ./config:/etc/bind
      - ./records:/var/lib/bind
      - ./cache:/var/cache/bind
    restart: always
