name: Build and Configure dnsmasq
on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dnsmasq
        run: |
          sudo apt-get update
          sudo apt-get install -y dnsmasq

      - name: Start dnsmasq (ignoring port conflicts)
        run: |
          sudo systemctl start dnsmasq || true
