name: Build and Configure dnsmasq
on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dnsmasq
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          git clone git://thekelleys.org.uk/dnsmasq.git 

