on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:
    branches:
      - main
      - master

name: Build
runs-on: ubuntu-latest
steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Install dnsmasq
    run: |
      sudo apt-get update
      sudo apt-get install -y dnsmasq
      sudo systemctl enable dnsmasq
      sudo systemctl start dnsmasq

