name: Build and Configure dnsmasq
on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dnsmasq
        run: |
          sudo apt-get update
          sudo apt-get install -y dnsmasq

      - name: Configure dnsmasq
        run: |
          # Modify dnsmasq configuration to use a different port
          sudo sed -i 's/#port=5353/port=5354/' /etc/dnsmasq.conf

      - name: Start dnsmasq
        run: sudo systemctl start dnsmasq
