name: Build and Configure dnsmasq
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use the script
        run: |
          sudo chmod +x ./SSL/SSL-General-Creation.sh
          sudo ./SSL/SSL-General-Creation.sh "$CERTIFICATE_NAME" "$DOMAIN_NAME"
        env:
          CERTIFICATE_NAME: My_Certificate
          DOMAIN_NAME: example.com
